server_name: "Fire C2"
server_base_url: "http://localhost:1234"
server_live_url: "http://localhost:1234"
server_private_url: "http://192.168.1.23:1234"
server_public_url: "https://fc2.example.com"
server_port: "1234"
server_api_key: "asdf"
browser_api_key: "asdf"
server_login_url_prefix: "asdf"
server_cookie_name: "fire-c2-server"
server_cookie_secret: "asdf"
server_cookie_secret_message: "asdf"
admin_username: "asdf"
admin_password: "asdf"
time_zone: "America/New_York"
save_files_path: "/home/morphs/SAVE_FILES"
bolt_db_path: "bolt.db"
encryption_key: "asdf"
redis_address: "localhost:6379"
# redis_address: "private-redis:6379"
redis_db_number: 1
redis_password: ""
ms_server_url: "http://192.168.1.21:1235"
restream_server_url_local: "http://restreamer:1235"
restream_server_url: "http://192.168.1.23:1235"
restream_server_api_key: "asdf"
restream_server_hls_url_prefix: "asdf"
stream_deck_server_url: "http://localhost:1234"
stream_deck_server_api_key: "asdf"
firecube_total_user_profiles: 2
firecube_user_profile_index: 0
tv:
  brand: "IR+HDMICEC"
  ip: "192.168.1.123"
  mac: "00:00:00:00:00:00"
  timeout_seconds: 10
  default_input: 1
  default_volume: 11
  volume_reset_limit: 30
  wake_on_lan: true
  lg_websocket_port: 3000
  lg_client_key: "asdf"
  vizio_auth_token: "asdf"
  ir:
    key_save_file_base_path: "./KEYS"
    default_remote: "samsung"
    remotes:
      samsung:
        keys:
          power:
            code: "necx:0x70702"
          volume_up:
            code: "necx:0x70707"
          volume_down:
            code: "necx:0x7070b"
          mute:
            code: "necx:0x7070f"
          left:
            code: "necx:0x70765"
          right:
            code: "necx:0x70762"
          up:
            code: "necx:0x70760"
          down:
            code: "necx:0x70761"
          enter:
            code: "necx:0x70768"
          return:
            code: "necx:0x70758"
          exit:
            code: "necx:0x7072d"
          menu:
            code: "necx:0x7071a"
          source:
            code: "necx:0x70701"
          test_raw:
            key_path: "test_raw"
adb:
  path: "/usr/local/bin/adb"
  connection_type: "tcp" # tcp or usb
  server_ip: "192.168.4.193" # 7291 - 6103-3 firecube
  # server_ip: "192.168.4.56" # 7291 - firestick
  # server_ip: "192.168.4.124" # 7291 - firetablet-14
  server_port: "5555"
  serial: "GCC0X8081307034C"
  timeout_seconds: 4
  device_type: "firecube" # firecube , firestick , firetablet
  apks:
    disney:
      firecube:
        package: "com.disney.disneyplus"
        activities:
          main: "com.bamtechmedia.dominguez.main.MainActivity"
          playing: "com.bamtechmedia.dominguez.player.ui.experiences.legacy.v1.TvPlaybackActivity"
      firestick:
        package: "com.disney.disneyplus"
        activities:
          main: "com.bamtechmedia.dominguez.main.MainActivity"
      firetablet:
        package: "com.disney.disneyplus"
        activities:
          main: "com.bamtechmedia.dominguez.main.MainActivity"
          playing: "com.bamtechmedia.dominguez.player.ui.experiences.legacy.v1.MobilePlaybackActivity"
    hulu:
      firecube:
        package: "com.hulu.plus"
        activities:
          main: "com.hulu.plus.MainActivity"
      firestick:
        package: "com.hulu.plus"
        activities:
          main: "com.hulu.plus.MainActivity"
      firetablet:
        package: "com.hulu.plus"
        activities:
          main: "com.hulu.features.playback.PlayerActivity"
          temp: "com.hulu.plus.SplashActivity"
    netflix:
      firecube:
        package: "com.netflix.ninja"
        activities:
          main: "com.netflix.ninja.MainActivity"
          source: "com.netflix.ninja/.MainActivity"
      firestick:
        package: "com.netflix.ninja"
        activities:
          main: "com.netflix.ninja.MainActivity"
          source: "com.netflix.ninja/.MainActivity"
      firetablet:
        package: "com.netflix.mediaclient"
        activities:
          main: "com.netflix.mediaclient.ui.player.PlayerActivity"
          source: "com.netflix.mediaclient.ui.player.PlayerActivity"
          sign_in: "o.bZb"
          profile_selection: "com.netflix.mediaclient.ui.profiles.ProfileSelectionActivity"
          home: "com.netflix.mediaclient.ui.home.HomeActivity"
    spotify:
      firecube:
        package: "com.spotify.music"
        activities:
          main: "com.spotify.music.MainActivity"
      firestick:
        package: "com.spotify.music"
        activities:
          main: "com.spotify.tv.android.SpotifyTVActivity"
      firetablet:
        package: "com.spotify.music"
        activities:
          main: "com.spotify.music.MainActivity"
    twitch:
      firecube:
        package: "tv.twitch.android.app"
        activities:
          main: "tv.twitch.starshot64.app.StarshotActivity"
      firestick:
        package: "tv.twitch.android.app"
        activities:
          main: "tv.twitch.starshot64.app.StarshotActivity"
      firetablet:
        package: "tv.twitch.android.app"
        activities:
          main: "tv.twitch.android.feature.viewer.main.MainActivity"
    youtube:
      firecube:
        package: "com.amazon.firetv.youtube"
        activities:
          main: "dev.cobalt.app.MainActivity"
      firestick:
        package: "com.amazon.firetv.youtube"
        activities:
          main: "dev.cobalt.app.MainActivity"
      firetablet: # not available
        package: "com.amazon.firetv.youtube"
        activities:
          main: "dev.cobalt.app.MainActivity"
    vlc:
      firecube:
        package: "org.videolan.vlc"
        activities:
          main: "org.videolan.television.ui.MainTvActivity"
      firestick:
        package: "org.videolan.vlc"
        activities:
          main: "org.videolan.vlc.StartActivity"
      firetablet:
        package: "org.videolan.vlc"
        activities:
          main: "org.videolan.vlc.gui.MainActivity"
hulu_total_user_profiles: 5
hulu_user_profile_index: 4
youtube_api_keys:
  - asdf-1
  - asdf-2
twitch_user_id: "asdf"
twitch_client_id: "asdf"
twitch_client_secret: "asdf"
twitch_oauth_token: "asdf"
twitch_access_token: "asdf"
twitch_refresh_token: "asdf"